import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

import { TASK_STATUSES } from 'src/shared/lib/constants';
import Navbar from 'src/shared/components/Navigation/Navbar';
import NavItem from 'src/shared/components/Navigation/NavItem';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="flex flex-col items-center justify-center gap-y-3 p-3">
          <h3 className="mt-3 text-3xl font-extrabold tracking-tight">
            The Task List View
          </h3>
          {/* tasks nav */}
          <Navbar>
            <NavItem href="/" title="All" />
            {TASK_STATUSES.map(status => {
              return (
                <NavItem
                  key={status.label.toLowerCase()}
                  href={`/tasks/${status.value}`}
                  title={status.label}
                />
              );
            })}
          </Navbar>
        </header>

        <main className="p-4 font-[family-name:var(--font-geist-sans)]">
          {children}
        </main>

        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
          <span>&copy; {new Date().getFullYear()}</span>
        </footer>
      </body>
    </html>
  );
}
